name: gromacs-build-mo833
on: [push]
jobs:
  build-gromacs:
    runs-on: ubuntu:latest
    steps:
      #checks out
      - uses: actions/checkout@v3
      #update and isntal wget and git
      - run: apt update && apt-get -y install wget git
      #install cmake
      - run: apt-get -y install build-essential libssl-dev cmake
      #build
      - run: mkdir build && cd build && cmake .. -DGMX_BUILD_OWN_FFTW=ON -DREGRESSIONTEST_DOWNLOAD=ON && make && make check ; sudo make install && source /usr/local/gromacs/bin/GMXRC
